[tools]
python = "3.12.9"
uv = "latest"


[env]
_.path = ["./.venv", "./.venv/Scripts"]
UV_LINK_MODE="copy"

[tasks.compile]
run = "uv run pyinstaller --onefile --name drlua --distpath dist drlua/cli.py"
