from __future__ import annotations

import json
import os
import shutil
import subprocess
from typing import TypedDict

from datetime import datetime
from fractions import Fraction
from pathlib import Path

from loguru import logger
from tqdm import tqdm
from drlua.config import PROCESSED_DATA_DIR, SUPPORTED_EXTENSIONS, SCENE_NAME_SEP, DateFormatTyperOption, LUA_SHARED_DIR

import typer

from drlua.helpers import luautil
from drlua.helpers.luautil import lua_string
from drlua.helpers.binutil import ClipDataInput, ClipBinGroup
from drlua.helpers.distribute import VideoItem, split_videos_by_frame_count
from drlua.helpers.scenerules import NameTag, ReleaseName
create_bins_app = typer.Typer()

class GroupedBucket(TypedDict):
    clips: list[ClipDataInput]
    total_frames: int

def render_lua(
    output_path: Path,
    source_folder: Path,
    release_name: ReleaseName,
    clip_bin_groups: list[ClipBinGroup],
    timelines: bool,
    include_kinds: list[str],
) -> str:
    payload_bins: list[dict[str, object]] = []
    for clips_bin in tqdm(clip_bin_groups, position=0):
        if clips_bin.layer >= 1 and clips_bin.layer <= 26:
            layer_suffix = chr(ord("A") + clips_bin.layer - 1)
        else:
            layer_suffix = str(clips_bin.layer)
        payload_bins.append(
            {
                "name": f"{release_name.parent_text()}_{clips_bin.kind}_{layer_suffix}",
                "release_name": clips_bin.release_name,
                "parent": clips_bin.parent,
                "date": clips_bin.date,
                "title": clips_bin.title,
                "section": clips_bin.section,
                "tags": clips_bin.tags or [],
                "group": clips_bin.group,
                "kind": clips_bin.kind,
                "layer": clips_bin.layer,
                "totalFrames": clips_bin.total_frames,
                "clips": [
                    {
                        "path": str(clip.path),
                        "frames": clip.frames,
                    }
                    for clip in clips_bin.clips
                ],
            }
        )

    payload = {
        "create_timelines": timelines,
        "scene_rules_sep": SCENE_NAME_SEP,
        "source_folder": str(source_folder),
        "parent_bin_name": release_name.parent_text(),
        "release_name": release_name.text(),
        "include_kinds": include_kinds,
        "bins": payload_bins,
    }
    payload_json = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))

    lines = [
        "-- Generated by create_bins_lua.py",
        "-- Paste into the DaVinci Resolve Lua console to run this file:",
        f"-- dofile([[{output_path.resolve()}]])",
        f"-- Source folder: {source_folder}",
        f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"local create_bins = dofile([[{(LUA_SHARED_DIR / 'bins.lua').resolve()}]])",
        "",
        f"local payload_json = {lua_string(payload_json)}",
        "",
        "create_bins(payload_json)",
    ]

    return "\n".join(lines)



@create_bins_app.command()
def create_bins(
    input_folder: Path = typer.Argument(..., exists=True, dir_okay=True, file_okay=False, resolve_path=True),
    name: str = typer.Option(..., "--name"),
    section: str | None = typer.Option(None, "--section"),
    group_name: str | None = typer.Option(None, "--group"),
    tag: list[str] = typer.Option([], "--tag"),
    date_format: DateFormatTyperOption = typer.Option(DateFormatTyperOption.long, '--date', show_default=True),
    recursive: bool = typer.Option(True, "--recursive", metavar="FLAG"),
    copy: bool = typer.Option(False, "--copy", metavar="FLAG"),
    only_vertical: bool = typer.Option(False, "--only-vertical", "--vertical-only", "--vertical"),
    only_full: bool = typer.Option(False, "--only-full-size"),
    only_bins: bool = typer.Option(False, "--only-bins", metavar="FLAG", show_default=True),
):
    input_folder = input_folder.expanduser().resolve()
    if not input_folder.exists() or not input_folder.is_dir():
        raise RuntimeError(f"Input folder does not exist or is not a directory: {input_folder}")

    ffprobe_path = shutil.which("ffprobe")
    if not ffprobe_path:
        raise RuntimeError(f"ffprobe not found: {ffprobe_path}")

    if recursive:
        media_files: list[Path] = []
        for root, _, files in tqdm(os.walk(input_folder), desc="walk", position=0, unit="dir"):
            root_path = Path(root)
            for file_name in tqdm(files, position=1, leave=False, unit="file"):
                file_path = (root_path / file_name).resolve()
                if file_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(file_path)
    else:
        media_files = []
        with os.scandir(input_folder) as entries:
            for entry in tqdm(entries, desc="scandir"):
                if not entry.is_file():
                    continue
                file_path = Path(entry.path).resolve()
                if file_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(file_path)

    clips: list[ClipDataInput] = []
    media_file_count = 0
    for media_file in tqdm(media_files, desc="ffprobe", unit="clip", position=0):
        media_file_count += 1
        result = subprocess.run(
            [
                ffprobe_path,
                "-v",
                "error",
                "-show_entries",
                "stream=codec_type,codec_name,width,height,nb_frames,avg_frame_rate,r_frame_rate,duration:format=duration",
                "-of",
                "json",
                str(media_file),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            continue

        file_stat = media_file.stat()
        file_size = file_stat.st_size
        file_ext = media_file.suffix.lower()
        file_birth_ts = getattr(file_stat, "st_birthtime", file_stat.st_mtime)
        file_birth_date = datetime.fromtimestamp(file_birth_ts).isoformat(timespec="seconds")

        try:
            payload = json.loads(result.stdout)
            streams = payload.get("streams") or []
            video_stream = next((item for item in streams if item.get("codec_type") == "video"), None)
            if video_stream is None:
                raise ValueError("missing video stream")
            audio_stream = next((item for item in streams if item.get("codec_type") == "audio"), None)

            width = int(video_stream.get("width") or 0)
            height = int(video_stream.get("height") or 0)
            fps_text = video_stream.get("avg_frame_rate") or video_stream.get("r_frame_rate") or "0/0"
            fps = float(Fraction(str(fps_text))) if fps_text not in {"0/0", "", "0"} else 0.0
            frames_text = str(video_stream.get("nb_frames") or "").strip()
            frames = int(frames_text) if frames_text.isdigit() else 0
            duration = float(video_stream.get("duration") or (payload.get("format") or {}).get("duration") or 0)
            video_codec = str(video_stream.get("codec_name") or "unknown")
            audio_codec = str(audio_stream.get("codec_name") or "noaudio") if audio_stream else "noaudio"
            if not frames:
                frames = round(float(duration) * fps) if fps and duration else 0
            if frames <= 0:
                raise ValueError("missing usable frame metadata")
        except Exception:
            continue

        clips.append(
            ClipDataInput(
                path=media_file,
                frames=frames,
                fps=fps,
                video_codec=video_codec,
                audio_codec=audio_codec,
                width=width,
                height=height,
                kind="Vertical" if height > width else "Full",
                file_size=file_size,
                file_ext=file_ext,
                file_created=file_birth_date,
            )
        )

    if media_file_count == 0:
        raise RuntimeError(f"No supported media files found in {input_folder}")
    if len(clips) < 3:
        raise RuntimeError(f"Need at least 3 readable video clips; found {len(clips)}.")

    release_name = ReleaseName()
    release_name.addRoleValue(NameTag.Role.Name, name)
    if date_format == DateFormatTyperOption.long:
        release_name.addRoleValue(NameTag.Role.LongDate, True)
    elif date_format == DateFormatTyperOption.short:
        release_name.addRoleValue(NameTag.Role.ShortDate, True)
    for item in tag:
        release_name.addRoleValue(NameTag.Role.Tag, item)
    release_name.addRoleValue(NameTag.Role.Section, section)
    release_name.addRoleValue(NameTag.Role.Group, group_name)

    include_kinds: list[str] = []
    if only_vertical:
        include_kinds.append("Vertical")
    if only_full:
        include_kinds.append("Full")
    if not include_kinds:
        include_kinds = ["Vertical", "Full"]

    clips_sorted = sorted(clips, key=lambda item: (-item.frames, item.path.name.lower()))
    video_items = [VideoItem(filename=str(clip.path), frame_length=clip.frames) for clip in clips_sorted]
    grouped_videos = split_videos_by_frame_count(video_items, group_count=3)
    clips_by_path = {str(clip.path): clip for clip in clips}

    grouped_bins: list[GroupedBucket] = []
    for video_group in grouped_videos:
        bucket_clips = [clips_by_path[video.filename] for video in video_group]
        grouped_bins.append(
            {
                "clips": bucket_clips,
                "total_frames": sum(video.frame_length for video in video_group),
            }
        )

    parent_name = release_name.parent_text()
    date_text = release_name.textWithRole(NameTag.Role.LongDate) or release_name.textWithRole(NameTag.Role.ShortDate)
    title_text = release_name.textWithRole(NameTag.Role.Title)
    release_text = release_name.text()
    tags = [tag_item.text() for tag_item in release_name.tagsWithRole(NameTag.Role.Tag)]
    section_text = release_name.textWithRole(NameTag.Role.Section)
    group_text = release_name.textWithRole(NameTag.Role.Group)

    output_bins: list[ClipBinGroup] = []
    for layer, bucket in tqdm(enumerate(sorted(grouped_bins, key=lambda item: item["total_frames"]), start=1), desc="layer buckets"):
        vertical = [clip for clip in bucket["clips"] if clip.kind == "Vertical"]
        full = [clip for clip in bucket["clips"] if clip.kind == "Full"]
        vertical.sort(key=lambda item: (item.frames, item.path.name.lower()))
        full.sort(key=lambda item: (item.frames, item.path.name.lower()))
        if "Vertical" in include_kinds:
            output_bins.append(
                ClipBinGroup(
                    kind="Vertical",
                    parent=parent_name,
                    date=date_text,
                    title=title_text,
                    release_name=release_text,
                    tags=tags or None,
                    section=section_text,
                    group=group_text,
                    layer=layer,
                    clips=vertical,
                    total_frames=sum(clip.frames for clip in vertical),
                )
            )
        if "Full" in include_kinds:
            output_bins.append(
                ClipBinGroup(
                    kind="Full",
                    parent=parent_name,
                    date=date_text,
                    title=title_text,
                    release_name=release_text,
                    tags=tags or None,
                    section=section_text,
                    group=group_text,
                    layer=layer,
                    clips=full,
                    total_frames=sum(clip.frames for clip in full),
                )
            )

    output_path = PROCESSED_DATA_DIR / "create_bins" / release_name.file_name()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_lua(output_path, input_folder, release_name, output_bins, not only_bins, include_kinds),
        encoding="utf-8",
        newline="\n",
    )

    typer.echo(f"Wrote Lua script: {output_path}")
    logger.success(f"Wrote Lua script: {output_path}")
    typer.echo(luautil.lua_dofile_hint(output_path, copy))
