from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
import os
import shutil
import subprocess
import sys

from datetime import datetime
from fractions import Fraction
from pathlib import Path, PurePosixPath

from loguru import logger
from drlua.config import (
    LUA_DIR,
    PROCESSED_DATA_DIR,
    SCENE_NAME_SEP,
    STASH_MAP,
    SUPPORTED_EXTENSIONS,
)

from drlua.helpers.distribute import VideoItem, split_videos_by_frame_count
from drlua.helpers.scenerules import NameTag, ReleaseName

import luadata
from drlua import __version__


def lua_header(release_name:ReleaseName, input_location: str|Path, outfile:str|Path):
    from datetime import datetime
    outfile = Path(outfile)
    lines = [
        f"-- Generated by DrLua v{__version__}",
        f"--    Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"-- Input: {str(input_location)}",
        f"-- Output: '{outfile.as_posix()}'",
        f"-- Release: {release_name.text()}",
        f"--    NameTags: {json.dumps(release_name.text_name_tags())}",
        "",
        r"-- Instructions:",
        r"--    Paste into the DaVinci Resolve Lua console to run this file:",
        r"---   ```lua",
        f"--        dofile([[{outfile.resolve()}]])",
        r"---   ```",
    ]
    return "\n".join(lines)


@dataclass
class ClipDataInput:
    path: Path
    frames: int
    fps: float
    video_codec: str
    audio_codec: str
    width: int
    height: int
    kind: str
    file_size: int
    file_ext: str
    file_created: str

@dataclass
class ClipBinGroup:
    date: str|None
    kind: str
    layer: int
    parent: str
    release_name: str
    clips: list[ClipDataInput]
    total_frames: int

@dataclass(slots=True)
class Payload:
    create_timelines: bool
    scene_rules_sep: str
    parent_bin_name: str
    release_name: str
    include_kinds: list[str]
    bins: list[dict[str, object]] = field(default_factory=list)

def make_include_kinds_from_args(vertical_only, full_only):
    include_kinds: list[str] = []
    if vertical_only:
        include_kinds.append("Vertical")
    if full_only:
        include_kinds.append("Full")
    if not include_kinds:
        include_kinds = ["Vertical", "Full"]
    return include_kinds


def collect_folder_media_files(input_path: Path, recursive:bool=True):
    input_path = Path(input_path).expanduser().resolve()
    media_files: list[Path] = []
    if recursive:
        for root, _, files in os.walk(input_path):
            root_path = Path(root)
            for file_name in files:
                input_path = (root_path / file_name).resolve()
                if input_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(input_path)
    else:
        with os.scandir(input_path) as entries:
            for entry in entries:
                if not entry.is_file():
                    continue
                input_path = Path(entry.path).resolve()
                if input_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(input_path)
    return media_files

def collect_efu_media_files(input_file: Path):
    import csv
    media_files: list[Path] = []
    with input_file.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle)
        header = next(reader, None)
        if header is None or not header or header[0] != "Filename":
            raise RuntimeError(f"Unsupported EFU header in {input_file}")

        for row in reader:
            if not row:
                continue
            raw_path = row[0].strip()
            if not raw_path:
                continue

            media_file = Path(raw_path).expanduser()
            if media_file.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            if not media_file.exists() or not media_file.is_file():
                continue
            media_files.append(media_file.resolve())
    return media_files

def collect_metadata_csv_media_files(input_file: Path):
    import csv
    media_files: list[Path] = []
    with input_file.open("r", encoding="utf-16", newline="") as handle:
        for row in csv.DictReader(handle):
            media_file = (Path(row["Clip Directory"].strip()) / row["File Name"].strip()).resolve()
            if media_file.suffix.lower() in SUPPORTED_EXTENSIONS:
                media_files.append(media_file)
    return media_files

def collect_stash_export_media_files(input_path: Path):
    def map_stash_path(raw_path: str) -> Path | None:
        posix_path = PurePosixPath(raw_path.strip())

        for stash_prefix, local_prefix in STASH_MAP.items():
            stash_parts = PurePosixPath(stash_prefix).parts
            if posix_path.parts[: len(stash_parts)] != stash_parts:
                continue

            relative_parts = posix_path.parts[len(stash_parts) :]
            return Path(local_prefix, *relative_parts).expanduser()

        if ":" in raw_path:
            return Path(raw_path).expanduser()

        return Path(*posix_path.parts[1:]).expanduser() if posix_path.is_absolute() else Path(*posix_path.parts).expanduser()

    media_files: list[Path] = []
    export_jsons = [input_path] if input_path.is_file() else input_path.glob("**/*.json")
    for export_json in export_jsons:
        with export_json.open("r", encoding="utf-8") as fp:
            data = json.load(fp)

        for raw_path in data.get("files", []):
            if not isinstance(raw_path, str) or not raw_path.strip():
                continue

            media_file = map_stash_path(raw_path)
            if media_file is None:
                continue
            if media_file.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            if not media_file.exists() or not media_file.is_file():
                continue
            media_files.append(media_file.resolve())

    return media_files


def probe_media_files_to_clips(media_files: list[Path]) -> list[ClipDataInput]:
    clips: list[ClipDataInput] = []
    ffprobe_path = (
        str(Path(sys._MEIPASS) / "tools" / "ffmpeg" / "ffprobe.exe")
        if getattr(sys, "frozen", False)
        else shutil.which("ffprobe")
    )
    if not ffprobe_path:
        raise RuntimeError(f"ffprobe not found: {ffprobe_path}")
    for media_file in media_files:
        logger.info("Probing {}", media_file)
        result = subprocess.run(
            [
                ffprobe_path,
                "-v",
                "error",
                "-show_entries",
                "stream=codec_type,codec_name,width,height,nb_frames,avg_frame_rate,r_frame_rate,duration:format=duration",
                "-of",
                "json",
                str(media_file),
            ],
            capture_output=True,
            text=True,
            check=False,
            creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0,
        )
        if result.returncode != 0:
            continue

        file_stat = media_file.stat()
        file_size = file_stat.st_size
        file_ext = media_file.suffix.lower()
        file_birth_ts = getattr(file_stat, "st_birthtime", file_stat.st_mtime)
        file_birth_date = datetime.fromtimestamp(file_birth_ts).isoformat(timespec="seconds")

        try:
            payload = json.loads(result.stdout)
            streams = payload.get("streams") or []
            video_stream = next((item for item in streams if item.get("codec_type") == "video"), None)
            if video_stream is None:
                raise ValueError("missing video stream")
            audio_stream = next((item for item in streams if item.get("codec_type") == "audio"), None)

            width = int(video_stream.get("width") or 0)
            height = int(video_stream.get("height") or 0)
            fps_text = video_stream.get("avg_frame_rate") or video_stream.get("r_frame_rate") or "0/0"
            fps = float(Fraction(str(fps_text))) if fps_text not in {"0/0", "", "0"} else 0.0
            frames_text = str(video_stream.get("nb_frames") or "").strip()
            frames = int(frames_text) if frames_text.isdigit() else 0
            duration = float(video_stream.get("duration") or (payload.get("format") or {}).get("duration") or 0)
            video_codec = str(video_stream.get("codec_name") or "unknown")
            audio_codec = str(audio_stream.get("codec_name") or "noaudio") if audio_stream else "noaudio"
            if not frames:
                frames = round(float(duration) * fps) if fps and duration else 0
            if frames <= 0:
                raise ValueError("missing usable frame metadata")
        except Exception:
            continue

        clips.append(
            ClipDataInput(
                path=media_file,
                frames=frames,
                fps=fps,
                video_codec=video_codec,
                audio_codec=audio_codec,
                width=width,
                height=height,
                kind="Vertical" if height > width else "Full",
                file_size=file_size,
                file_ext=file_ext,
                file_created=file_birth_date,
            )
        )
    return clips

def make_bin_groups(clips, release_name: ReleaseName, include_kinds):
    logger.trace(f"[make_bin_groups] clips {clips}")
    parent_name = release_name.parent_text()
    release_text = release_name.text()
    clips_sorted = sorted(clips, key=lambda item: (-item.frames, item.path.name.lower()))
    video_items = [VideoItem(filename=str(clip.path), frame_length=clip.frames) for clip in clips_sorted]
    grouped_videos = split_videos_by_frame_count(video_items, group_count=3)
    clips_by_path = {str(clip.path): clip for clip in clips}

    grouped_bins= []
    for video_group in grouped_videos:
        bucket_clips = [clips_by_path[video.filename] for video in video_group]
        grouped_bins.append(
            {
                "clips": bucket_clips,
                "total_frames": sum(video.frame_length for video in video_group),
            }
        )

    output_bins: list[ClipBinGroup] = []
    for layer, bucket in enumerate(sorted(grouped_bins, key=lambda item: item["total_frames"]), start=1):
        vertical = [clip for clip in bucket["clips"] if clip.kind == "Vertical"]
        full = [clip for clip in bucket["clips"] if clip.kind == "Full"]
        vertical.sort(key=lambda item: (item.frames, item.path.name.lower()))
        full.sort(key=lambda item: (item.frames, item.path.name.lower()))
        if "Vertical" in include_kinds and vertical:
            output_bins.append(
                ClipBinGroup(
                    clips=vertical,
                    date=release_name.textWithRole(NameTag.Role.ShortDate),
                    kind="Vertical",
                    layer=layer,
                    parent=parent_name,
                    release_name=release_text,
                    total_frames=sum(clip.frames for clip in vertical),
                )
            )
        if "Full" in include_kinds and full:
            output_bins.append(
                ClipBinGroup(
                    clips=full,
                    date=release_name.textWithRole(NameTag.Role.LongDate),
                    kind="Full",
                    layer=layer,
                    parent=parent_name,
                    release_name=release_text,
                    total_frames=sum(clip.frames for clip in full),
                )
            )
    return output_bins

def make_payload(
    release_name: ReleaseName,
    bin_groups: list[ClipBinGroup],
    timelines: bool,
    include_kinds: list[str],
):
    payload_bins: list[dict[str, object]] = []
    logger.trace(f"[make_payload] bin_groups {bin_groups}")

    for index, clips_bin in enumerate(bin_groups):
        if index >= 1 and index <= 26:
            layer_suffix = chr(ord("A") + index - 1)
        else:
            layer_suffix = str(index)
        payload_bins.append(
            {
                "kind": clips_bin.kind,
                "layer_suffix": layer_suffix,
                "name": f"{release_name.parent_text()}_{clips_bin.kind}_{layer_suffix}",
                "parent": clips_bin.parent,
                "release_name": clips_bin.release_name,
                "totalFrames": clips_bin.total_frames,
                "clips": [
                    {
                        "path": str(clip.path),
                        "frames": clip.frames,
                    }
                    for clip in clips_bin.clips
                ],
            }
        )

    return asdict(Payload(
        create_timelines=timelines,
        scene_rules_sep=SCENE_NAME_SEP,
        parent_bin_name=release_name.parent_text(),
        release_name=release_name.text(),
        include_kinds=include_kinds,
        bins=payload_bins,
    ))

def create_bins(
    from_locations: list[Path],
    name: str,
    section: str,
    tag: list[str] | None = None,
    group_name: str | None = None,
    recursive: bool = True,
    vertical_only: bool = False,
    full_only: bool = False,
    bins_only: bool = False,
) -> None:
    tag = list(tag or [])
    input_locations = [Path(from_location).expanduser().resolve() for from_location in from_locations]
    name = name.strip()
    section = section.strip()
    tag = [item.strip() for item in tag if item and item.strip()]

    logger.debug(f"Collecting from {input_locations}")

    media_files = []
    for input_location_item in input_locations:
        if input_location_item.is_dir():
            collected_files = collect_folder_media_files(input_location_item, recursive)
            if len(collected_files) == 0 and len(list(input_location_item.glob("**/*.json"))) > 0:
                collected_files = collect_stash_export_media_files(input_location_item)
            media_files.extend(collected_files)
        elif input_location_item.suffix.lower() in SUPPORTED_EXTENSIONS:
            media_files.append(input_location_item)
        elif input_location_item.suffix.lower() == ".efu":
            media_files.extend(collect_efu_media_files(input_location_item))
        elif input_location_item.suffix.lower() == ".csv":
            media_files.extend(collect_metadata_csv_media_files(input_location_item))
        elif input_location_item.suffix.lower() == ".json":
            media_files.extend(collect_stash_export_media_files(input_location_item))
        else:
            raise RuntimeError("Could not process input location")

    if len(media_files) == 0:
        raise RuntimeError(f"No supported media files found in {input_locations}")

    logger.debug(f"Collected {len(media_files)} media files..")

    clips = probe_media_files_to_clips(media_files)

    if len(clips) == 0:
        raise RuntimeError(f"No readable video clips found in {input_locations}.")

    logger.info(f"Converted to {len(clips)} clips..")

    release_name = ReleaseName(**locals())
    logger.info(f"Release name {release_name.text()}")

    out_file_path = PROCESSED_DATA_DIR / "create_bins" / release_name.file_name()
    include_kinds = make_include_kinds_from_args(vertical_only, full_only)

    output_bins = make_bin_groups(clips, release_name, include_kinds)
    if len(output_bins) == 0:
        raise RuntimeError(f"No output bins could be created for kinds: {', '.join(include_kinds)}")
    logger.debug(f"Made bins({len(output_bins)}) with total_frames {[o.total_frames for o in output_bins]}")

    payload = make_payload(release_name, output_bins, not bins_only, include_kinds)
    logger.debug(f"Made payload for parent_bin_name={payload['parent_bin_name']}")
    if not payload:
        raise RuntimeError("payload empty")

    header = lua_header(release_name, input_locations, out_file_path)
    out_file_path.parent.mkdir(parents=True, exist_ok=True)

    drlua_lib = (LUA_DIR / "lib.lua").read_text(encoding="utf-8")

    output_lines = [
        header,
        drlua_lib,
        f'CreateBins({luadata.serialize(payload, encoding="utf-8", indent="\t", indent_level=0)})',
    ]

    output_lua = "\n".join(output_lines)

    out_file_path.write_text(output_lua, encoding="utf-8", newline="\n",)
    logger.success(f"Saved file {out_file_path.name}")
    dofile = f"\tdofile([[{out_file_path.expanduser().resolve().as_posix()}]])"
    hint = [
        "**Paste into the DaVinci Resolve Lua console:**",
        "```",
        dofile,
        "```",
    ]
    logger.info("\n".join(hint))
