from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
import os
import shutil
import subprocess

from datetime import datetime
from fractions import Fraction
from pathlib import Path, PurePosixPath

from loguru import logger
from tqdm import tqdm
from drlua.config import (
    LUA_DIR,
    PROCESSED_DATA_DIR,
    SCENE_NAME_SEP,
    STASH_MAP,
    SUPPORTED_EXTENSIONS,
)

from drlua.helpers.distribute import VideoItem, split_videos_by_frame_count
from drlua.helpers.scenerules import NameTag, ReleaseName

import luadata
from drlua import __version__


def _ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    while True:
        response = input(f"{prompt}{suffix} ").strip().lower()
        if not response:
            return default
        if response in {"y", "yes"}:
            return True
        if response in {"n", "no"}:
            return False


def default_release_name_from_input(input_location: Path) -> str:
    target = input_location.parent if input_location.is_file() else input_location
    if target.name:
        return target.name
    if input_location.is_file() and input_location.stem:
        return input_location.stem
    return target.anchor.rstrip("\\/") or "Release"


def prompt_for_section(section_tags: list[str]) -> str:
    other_label = "Other"
    choices = ", ".join(section_tags + [other_label])
    section_choice = input(f"Enter section ({choices}) [{section_tags[0]}]: ").strip()
    if not section_choice:
        return section_tags[0]
    if section_choice != other_label:
        return section_choice

    custom_section = ""
    while not custom_section:
        custom_section = input("Enter custom section: ").strip()
    return custom_section


def prompt_for_tags() -> list[str]:
    tags: list[str] = []
    while True:
        tag_value = input("Enter tag (leave blank to continue): ").strip()
        if not tag_value:
            return tags
        tags.append(tag_value)


def lua_header(release_name:ReleaseName, input_location: str|Path, outfile:str|Path):
    from datetime import datetime
    outfile = Path(outfile)
    lines = [
        f"-- Generated by DrLua v{__version__}",
        f"--    Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"-- Input: {str(input_location)}",
        f"-- Output: '{outfile.as_posix()}'",
        f"-- Release: {release_name.text()}",
        f"--    NameTags: {json.dumps(release_name.text_name_tags())}",
        "",
        r"-- Instructions:",
        r"--    Paste into the DaVinci Resolve Lua console to run this file:",
        r"---   ```lua",
        f"--        dofile([[{outfile.resolve()}]])",
        r"---   ```",
    ]
    return "\n".join(lines)


@dataclass
class ClipDataInput:
    path: Path
    frames: int
    fps: float
    video_codec: str
    audio_codec: str
    width: int
    height: int
    kind: str
    file_size: int
    file_ext: str
    file_created: str

@dataclass
class ClipBinGroup:
    date: str|None
    kind: str
    layer: int
    parent: str
    release_name: str
    clips: list[ClipDataInput]
    total_frames: int

@dataclass(slots=True)
class Payload:
    create_timelines: bool
    scene_rules_sep: str
    parent_bin_name: str
    release_name: str
    include_kinds: list[str]
    bins: list[dict[str, object]] = field(default_factory=list)

def make_include_kinds_from_args(vertical_only, full_only):
    include_kinds: list[str] = []
    if vertical_only:
        include_kinds.append("Vertical")
    if full_only:
        include_kinds.append("Full")
    if not include_kinds:
        include_kinds = ["Vertical", "Full"]
    return include_kinds


def collect_folder_media_files(input_path: Path, recursive:bool=True):
    input_path = Path(input_path).expanduser().resolve()
    media_files: list[Path] = []
    if recursive:
        for root, _, files in tqdm(os.walk(input_path), desc="walk", position=0, unit=" dir"):
            root_path = Path(root)
            for file_name in tqdm(files, desc="collect", position=1, leave=False, unit=" file"):
                input_path = (root_path / file_name).resolve()
                if input_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(input_path)
    else:
        with os.scandir(input_path) as entries:
            for entry in tqdm(entries, desc="scan", position=0, unit=" file"):
                if not entry.is_file():
                    continue
                input_path = Path(entry.path).resolve()
                if input_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                    media_files.append(input_path)
    return media_files

def collect_efu_media_files(input_file: Path):
    import csv
    media_files: list[Path] = []
    with input_file.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle)
        header = next(reader, None)
        if header is None or not header or header[0] != "Filename":
            raise RuntimeError(f"Unsupported EFU header in {input_file}")

        for row in reader:
            if not row:
                continue
            raw_path = row[0].strip()
            if not raw_path:
                continue

            media_file = Path(raw_path).expanduser()
            if media_file.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            if not media_file.exists() or not media_file.is_file():
                continue
            media_files.append(media_file.resolve())
    return media_files

def collect_metadata_csv_media_files(input_file: Path):
    import csv
    media_files: list[Path] = []
    with input_file.open("r", encoding="utf-16", newline="") as handle:
        for row in csv.DictReader(handle):
            media_file = (Path(row["Clip Directory"].strip()) / row["File Name"].strip()).resolve()
            if media_file.suffix.lower() in SUPPORTED_EXTENSIONS:
                media_files.append(media_file)
    return media_files

def collect_stash_export_media_files(input_path: Path):
    def map_stash_path(raw_path: str) -> Path | None:
        posix_path = PurePosixPath(raw_path.strip())

        for stash_prefix, local_prefix in STASH_MAP.items():
            stash_parts = PurePosixPath(stash_prefix).parts
            if posix_path.parts[: len(stash_parts)] != stash_parts:
                continue

            relative_parts = posix_path.parts[len(stash_parts) :]
            return Path(local_prefix, *relative_parts).expanduser()

        if ":" in raw_path:
            return Path(raw_path).expanduser()

        return Path(*posix_path.parts[1:]).expanduser() if posix_path.is_absolute() else Path(*posix_path.parts).expanduser()

    media_files: list[Path] = []
    for export_json in input_path.glob("**/*.json"):
        with export_json.open("r", encoding="utf-8") as fp:
            data = json.load(fp)

        for raw_path in data.get("files", []):
            if not isinstance(raw_path, str) or not raw_path.strip():
                continue

            media_file = map_stash_path(raw_path)
            if media_file is None:
                continue
            if media_file.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            if not media_file.exists() or not media_file.is_file():
                continue
            media_files.append(media_file.resolve())

    return media_files


def probe_media_files_to_clips(media_files: list[Path]) -> list[ClipDataInput]:
    clips: list[ClipDataInput] = []
    ffprobe_path = shutil.which("ffprobe")
    if not ffprobe_path:
        raise RuntimeError(f"ffprobe not found: {ffprobe_path}")
    for media_file in tqdm(media_files, desc="ffprobe", unit=" clip", position=0):
        result = subprocess.run(
            [
                ffprobe_path,
                "-v",
                "error",
                "-show_entries",
                "stream=codec_type,codec_name,width,height,nb_frames,avg_frame_rate,r_frame_rate,duration:format=duration",
                "-of",
                "json",
                str(media_file),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            continue

        file_stat = media_file.stat()
        file_size = file_stat.st_size
        file_ext = media_file.suffix.lower()
        file_birth_ts = getattr(file_stat, "st_birthtime", file_stat.st_mtime)
        file_birth_date = datetime.fromtimestamp(file_birth_ts).isoformat(timespec="seconds")

        try:
            payload = json.loads(result.stdout)
            streams = payload.get("streams") or []
            video_stream = next((item for item in streams if item.get("codec_type") == "video"), None)
            if video_stream is None:
                raise ValueError("missing video stream")
            audio_stream = next((item for item in streams if item.get("codec_type") == "audio"), None)

            width = int(video_stream.get("width") or 0)
            height = int(video_stream.get("height") or 0)
            fps_text = video_stream.get("avg_frame_rate") or video_stream.get("r_frame_rate") or "0/0"
            fps = float(Fraction(str(fps_text))) if fps_text not in {"0/0", "", "0"} else 0.0
            frames_text = str(video_stream.get("nb_frames") or "").strip()
            frames = int(frames_text) if frames_text.isdigit() else 0
            duration = float(video_stream.get("duration") or (payload.get("format") or {}).get("duration") or 0)
            video_codec = str(video_stream.get("codec_name") or "unknown")
            audio_codec = str(audio_stream.get("codec_name") or "noaudio") if audio_stream else "noaudio"
            if not frames:
                frames = round(float(duration) * fps) if fps and duration else 0
            if frames <= 0:
                raise ValueError("missing usable frame metadata")
        except Exception:
            continue

        clips.append(
            ClipDataInput(
                path=media_file,
                frames=frames,
                fps=fps,
                video_codec=video_codec,
                audio_codec=audio_codec,
                width=width,
                height=height,
                kind="Vertical" if height > width else "Full",
                file_size=file_size,
                file_ext=file_ext,
                file_created=file_birth_date,
            )
        )
    return clips

def make_bin_groups(clips, release_name: ReleaseName, include_kinds):
    logger.trace(f"[make_bin_groups] clips {clips}")
    parent_name = release_name.parent_text()
    release_text = release_name.text()
    clips_sorted = sorted(clips, key=lambda item: (-item.frames, item.path.name.lower()))
    video_items = [VideoItem(filename=str(clip.path), frame_length=clip.frames) for clip in clips_sorted]
    grouped_videos = split_videos_by_frame_count(video_items, group_count=3)
    clips_by_path = {str(clip.path): clip for clip in clips}

    grouped_bins= []
    for video_group in grouped_videos:
        bucket_clips = [clips_by_path[video.filename] for video in video_group]
        grouped_bins.append(
            {
                "clips": bucket_clips,
                "total_frames": sum(video.frame_length for video in video_group),
            }
        )

    output_bins: list[ClipBinGroup] = []
    for layer, bucket in tqdm(enumerate(sorted(grouped_bins, key=lambda item: item["total_frames"]), start=1), desc="layer buckets"):
        vertical = [clip for clip in bucket["clips"] if clip.kind == "Vertical"]
        full = [clip for clip in bucket["clips"] if clip.kind == "Full"]
        vertical.sort(key=lambda item: (item.frames, item.path.name.lower()))
        full.sort(key=lambda item: (item.frames, item.path.name.lower()))
        if "Vertical" in include_kinds and vertical:
            output_bins.append(
                ClipBinGroup(
                    clips=vertical,
                    date=release_name.textWithRole(NameTag.Role.ShortDate),
                    kind="Vertical",
                    layer=layer,
                    parent=parent_name,
                    release_name=release_text,
                    total_frames=sum(clip.frames for clip in vertical),
                )
            )
        if "Full" in include_kinds and full:
            output_bins.append(
                ClipBinGroup(
                    clips=full,
                    date=release_name.textWithRole(NameTag.Role.LongDate),
                    kind="Full",
                    layer=layer,
                    parent=parent_name,
                    release_name=release_text,
                    total_frames=sum(clip.frames for clip in full),
                )
            )
    return output_bins

def make_payload(
    release_name: ReleaseName,
    bin_groups: list[ClipBinGroup],
    timelines: bool,
    include_kinds: list[str],
):
    payload_bins: list[dict[str, object]] = []
    logger.trace(f"[make_payload] bin_groups {bin_groups}")

    for index, clips_bin in tqdm(enumerate(bin_groups), position=0, desc="grouping", unit=" bin"):
        if index >= 1 and index <= 26:
            layer_suffix = chr(ord("A") + index - 1)
        else:
            layer_suffix = str(index)
        payload_bins.append(
            {
                "kind": clips_bin.kind,
                "layer_suffix": layer_suffix,
                "name": f"{release_name.parent_text()}_{clips_bin.kind}_{layer_suffix}",
                "parent": clips_bin.parent,
                "release_name": clips_bin.release_name,
                "totalFrames": clips_bin.total_frames,
                "clips": [
                    {
                        "path": str(clip.path),
                        "frames": clip.frames,
                    }
                    for clip in clips_bin.clips
                ],
            }
        )

    return asdict(Payload(
        create_timelines=timelines,
        scene_rules_sep=SCENE_NAME_SEP,
        parent_bin_name=release_name.parent_text(),
        release_name=release_name.text(),
        include_kinds=include_kinds,
        bins=payload_bins,
    ))

section_tags = ["Fansites", "Civilians", "Inspired"]


def create_bins(
    from_location: Path,
    name: str | None = None,
    section: str | None = None,
    tag: list[str] | None = None,
    group_name: str | None = None,
    recursive: bool = True,
    vertical_only: bool = False,
    full_only: bool = False,
    bins_only: bool = False,
    version: bool = False,
) -> int | None:
    if version:
        from drlua import __version__
        print(__version__)
        print(f"DrLua Version: {__version__}")
        return 0

    tag = list(tag or [])
    input_location = Path(from_location).expanduser().resolve()
    name = name.strip() if name else None
    section = section.strip() if section else None
    tag = [item.strip() for item in tag if item and item.strip()]

    media_files = []
    if input_location.is_file() and input_location.suffix in SUPPORTED_EXTENSIONS:
        print(f"Cannot use {input_location.suffix} file ({input_location.as_posix()})")
        use_parent = _ask_yes_no("Use file parent as input instead?")
        if use_parent:
            input_location = input_location.parent
        else:
            raise RuntimeError(f"No supported media files location provided. {input_location}")

    if not name:
        default_name = default_release_name_from_input(input_location)
        while not name:
            name = input(f"Enter name [{default_name}]: ").strip() or default_name
    if not section:
        section = prompt_for_section(section_tags)
    if not tag:
        tag = prompt_for_tags()

    logger.debug(f"Collecting from {input_location}")

    if input_location.is_dir():
        media_files = collect_folder_media_files(input_location, recursive)
        if len(media_files) == 0 and len(list(input_location.glob("**/*.json"))) > 0:
            media_files = collect_stash_export_media_files(input_location)
    elif input_location.is_file() and input_location.suffix == ".efu":
        media_files = collect_efu_media_files(input_location)
    elif input_location.is_file() and input_location.suffix == ".csv":
        media_files = collect_metadata_csv_media_files(input_location)
    else:
        raise RuntimeError("Could not process input location")

    if len(media_files) == 0:
        raise RuntimeError(f"No supported media files found in {input_location}")

    logger.debug(f"Collected {len(media_files)} media files..")

    clips = probe_media_files_to_clips(media_files)

    if len(clips) < 3:
        raise RuntimeError(f"Need at least 3 readable video clips; found {len(clips)}.")

    logger.info(f"Converted to {len(clips)} clips..")

    release_name = ReleaseName(**locals())
    logger.info(f"Release name {release_name.text()}")

    out_file_path = PROCESSED_DATA_DIR / "create_bins" / release_name.file_name()
    include_kinds = make_include_kinds_from_args(vertical_only, full_only)

    output_bins = make_bin_groups(clips, release_name, include_kinds)
    if len(output_bins) == 0:
        raise RuntimeError(f"No output bins could be created for kinds: {', '.join(include_kinds)}")
    logger.debug(f"Made bins({len(output_bins)}) with total_frames {[o.total_frames for o in output_bins]}")

    payload = make_payload(release_name, output_bins, not bins_only, include_kinds)
    logger.debug(f"Made payload for parent_bin_name={payload['parent_bin_name']}")
    if not payload:
        raise RuntimeError("payload empty")

    header = lua_header(release_name, input_location, out_file_path)
    out_file_path.parent.mkdir(parents=True, exist_ok=True)

    drlua_lib = (LUA_DIR / "lib.lua").read_text(encoding="utf-8")

    output_lines = [
        header,
        drlua_lib,
        f'CreateBins({luadata.serialize(payload, encoding="utf-8", indent="\t", indent_level=0)})',
    ]

    output_lua = "\n".join(output_lines)

    out_file_path.write_text(output_lua, encoding="utf-8", newline="\n",)
    logger.success(f"Saved file {out_file_path.name}")
    dofile = f"\tdofile([[{out_file_path.expanduser().resolve().as_posix()}]])"
    hint = [
        "**Paste into the DaVinci Resolve Lua console:**",
        "```",
        dofile,
        "```",
    ]
    print("\n".join(hint))
