from __future__ import annotations

from datetime import datetime
from pathlib import Path

from loguru import logger
import typer

from drlua.config import PROCESSED_DATA_DIR, DateFormatTyperOption
from drlua.helpers import luautil
from drlua.helpers.luautil import lua_string, read_lua_file
from drlua.helpers.scenerules import NameTag, ReleaseName


organize_media_bin_app = typer.Typer()

def render_lua(output_path: Path, input_bin_name: str, release_name: ReleaseName, timelines: bool) -> str:
    lines = [
        "-- Generated by organize_bin.py",
        "-- Paste into the DaVinci Resolve Lua console to run this file:",
        f"-- dofile([[{output_path.resolve()}]])",
        f"-- Input bin: {input_bin_name}",
        f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"CREATE_TIMELINES = {'true' if timelines else 'false'}",
        f"INPUT_BIN_NAME = {lua_string(input_bin_name)}",
        f"PARENT_BIN_NAME = {lua_string(release_name.parent_text())}",
        "",
    ]

    lines.extend(read_lua_file("organize_media_bin.lua").splitlines())
    return "\n".join(lines)


@organize_media_bin_app.command()
def organize_media_bin(
    input_bin_name: str = typer.Argument(..., help="Existing Media Pool bin name to reorganize."),
    name: str = typer.Option(..., "--name"),
    section: str | None = typer.Option(None, "--section"),
    group: str | None = typer.Option(None, "--group"),
    tag: list[str] = typer.Option([], "--tag"),
    date_format: DateFormatTyperOption = typer.Option(DateFormatTyperOption.long, '--date', show_default=True),
    recursive: bool = typer.Option(True, "--recursive", metavar="FLAG"),
    copy: bool = typer.Option(False, "--copy", metavar="FLAG"),
    only_bins: bool = typer.Option(False, "--only-bins", metavar="FLAG", show_default=True),
) -> None:
    release_name = ReleaseName()
    release_name.addRoleValue(NameTag.Role.Name, name or input_bin_name)
    if date_format == DateFormatTyperOption.long:
        release_name.addRoleValue(NameTag.Role.LongDate, True)
    elif date_format == DateFormatTyperOption.short:
        release_name.addRoleValue(NameTag.Role.ShortDate, True)
    for item in tag:
        release_name.addRoleValue(NameTag.Role.Tag, item)
    release_name.addRoleValue(NameTag.Role.Section, section)
    release_name.addRoleValue(NameTag.Role.Group, group)

    output_path = PROCESSED_DATA_DIR / "organize_bin" / release_name.file_name()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(
        render_lua(
            output_path=output_path,
            input_bin_name=input_bin_name,
            release_name=release_name,
            timelines=not only_bins,
        ),
        encoding="utf-8",
        newline="\n",
    )

    logger.success(f"Wrote Lua script: {output_path}")
    typer.echo(luautil.lua_dofile_hint(output_path, copy))
